import { fileURLToPath } from "node:url";
// Reviewed HTML editor equivalents of the former SVG authoring checks.
import process from "node:process";
import { Buffer } from "node:buffer";
import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { boot, createBlank, insert, snapshot, importDocument, fixture, records, downloadJson, openActions, openGroup, fillDuration, durationInputTotal } from "./editor-browser-helpers.mjs";
import { assertChecks } from "../../scripts/check-results.mjs";
const root = fileURLToPath(new URL("../../", import.meta.url));
const out = path.resolve(process.argv[2] ?? path.join(root, "artifacts", "browser")); const url = process.argv[3] ?? "http://localhost:5173/";
const errors = []; const checks = {}; const browser = await chromium.launch();
try {
  await mkdir(out, { recursive: true }); const { page, context } = await boot(browser, url, errors);
  try {
    await page.addInitScript(() => { const probe = { clicks: 0, revokes: 0, revokedInClickTask: false, anchorDetachedAtClick: false }; window.__downloadProbe = probe; let inClickTask = false;
      const click = HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click = function () { if (!this.hasAttribute("download")) return click.call(this); probe.clicks++; if (!this.isConnected) probe.anchorDetachedAtClick = true; inClickTask = true; try { return click.call(this); } finally { setTimeout(() => { inClickTask = false; }, 0); } };
      const revoke = URL.revokeObjectURL.bind(URL); URL.revokeObjectURL = (value) => { probe.revokes++; if (inClickTask) probe.revokedInClickTask = true; return revoke(value); };
    }); await page.reload(); await page.locator(".app-brand").waitFor();
    await createBlank(page); checks.HISTORY_BUTTONS_DISABLED_INITIALLY = await page.getByRole("button", { name: "Undo", exact: true }).isDisabled() && await page.getByRole("button", { name: "Redo", exact: true }).isDisabled();
    await page.getByLabel("Guide title", { exact: true }).fill("Kitchen reminder");
    await page.locator("[data-add-picture]").first().focus(); await page.keyboard.press("Enter");
    await page.getByRole("searchbox").fill("Onion"); await page.locator(".token-picker").getByRole("button", { name: "Onion", exact: true }).focus(); await page.keyboard.press("Enter");
    await page.locator("[data-editor-picture]").first().waitFor();
    await page.waitForFunction(() => document.activeElement === document.querySelector("[data-editor-picture]"));
    checks.KEYBOARD_CREATION_AND_INSERT_FOCUS = await page.locator("[data-editor-picture]").first().evaluate((node) => node === document.activeElement);
    await page.keyboard.press("Enter"); await page.getByLabel("Picture label", { exact: true }).waitFor();
    const longLabel = "WWWWWWWWWWWWWWWWWW vollständig – Öl & Gemüse \"quoted\"\nSecond line preserved";
    await page.getByLabel("Picture label", { exact: true }).fill(longLabel); checks.DIRECT_ACTIVATION_FULL_LABEL = (await snapshot(page)).steps[0].tokens[0].label === longLabel;
    checks.CORE_ATTACHMENTS_VISIBLE_WITHOUT_DISCLOSURE = await page.getByRole("group", { name: "Quantity", exact: true }).isVisible() && await page.getByRole("group", { name: "Time", exact: true }).isVisible() && await page.getByRole("group", { name: "Warning", exact: true }).isVisible();
    await openActions(page);
    await page.getByLabel("Optional note", { exact: true }).fill("N".repeat(400));
    const quantity = page.getByRole("group", { name: "Quantity", exact: true }); await quantity.getByLabel("Amount", { exact: true }).fill("0"); await quantity.getByRole("button", { name: "Save", exact: true }).click();
    checks.QUANTITY_VALIDATION_HAS_ACCESSIBLE_DESCRIPTION = await quantity.getByLabel("Amount", { exact: true }).evaluate((input) => input.getAttribute("aria-invalid") === "true" && !!document.getElementById(input.getAttribute("aria-describedby"))?.textContent);
    await quantity.getByLabel("Amount", { exact: true }).fill("7"); await quantity.getByLabel("Unit", { exact: true }).fill("odd imported scoops"); await quantity.getByRole("button", { name: "Save", exact: true }).click();
    const time = page.getByRole("group", { name: "Time", exact: true }); await time.getByLabel("Seconds", { exact: true }).fill("1.5"); await time.getByRole("button", { name: "Save", exact: true }).click();
    checks.DURATION_INTEGER_VALIDATION = await time.getByLabel("Seconds", { exact: true }).getAttribute("aria-invalid") === "true";
    await fillDuration(time, 90); await time.getByRole("button", { name: "Save", exact: true }).click();
    await page.getByRole("group", { name: "Warning", exact: true }).getByRole("combobox").selectOption("warning.sharp");
    await page.getByLabel("Warning label", { exact: true }).fill("Keep fingers clear");
    const attached = (await snapshot(page)).steps[0].tokens[0]; checks.ATTACHMENTS_WORKED_END_TO_END = attached.quantity.amount === 7 && attached.quantity.unit === "odd imported scoops" && attached.time.seconds === 90 && attached.warning.label === "Keep fingers clear" && attached.note.length === 400;
    await page.getByRole("button", { name: "Close", exact: true }).last().click();
    await page.locator("[data-editor-picture]").first().click();
    checks.ATTACHMENT_PREFILL_AND_NO_TRUNCATION = await page.getByLabel("Picture label", { exact: true }).inputValue() === longLabel && await page.getByLabel("Amount", { exact: true }).inputValue() === "7" && await page.getByLabel("Unit", { exact: true }).inputValue() === "odd imported scoops" && await durationInputTotal(time) === 90;
    await page.getByLabel("Picture label", { exact: true }).focus(); await page.keyboard.press("Control+c");
    checks.TEXT_FIELD_COPY_PRESERVES_DOCUMENT_CLIPBOARD = await page.evaluate(async () => (await import("/src/state/document.ts")).documentSession.copiedToken.peek() === null);
    await page.getByRole("button", { name: "Close", exact: true }).last().click(); await insert(page, "Chop");
    await page.locator("[data-editor-picture]").last().click(); await openActions(page); await page.getByRole("button", { name: "Move earlier", exact: true }).click();
    checks.FINAL_INDEX_FORWARD_BACKWARD_MOVE = (await snapshot(page)).steps[0].tokens[0].iconId === "action.chop";
    await page.locator("[data-editor-picture]").first().click(); await openActions(page); checks.MOVE_BOUNDARY_DISABLED = await page.getByRole("button", { name: "Move earlier", exact: true }).isDisabled();
    await page.getByRole("button", { name: "Move later", exact: true }).click();
    await page.getByRole("button", { name: "Undo", exact: true }).click(); await page.getByRole("button", { name: "Redo", exact: true }).click(); checks.UNDO_REDO_WORKED_END_TO_END = (await snapshot(page)).steps[0].tokens[1].iconId === "action.chop";
    await page.getByRole("button", { name: "Add step", exact: true }).click(); await page.getByLabel("Group title", { exact: true }).fill("Second destination"); await page.getByRole("button", { name: "Close", exact: true }).last().click();
    await page.locator("[data-editor-picture]").first().click(); await openActions(page); await page.locator(".editor-actions select").selectOption((await snapshot(page)).steps[1].id);
    checks.MOVE_TO_GROUP_PRESERVES_ATTACHMENTS = (await snapshot(page)).steps[1].tokens[0].quantity.unit === "odd imported scoops";
    await page.locator("[data-editor-picture]").last().focus(); await page.keyboard.press("Control+c"); await page.keyboard.press("Control+v");
    const copied = await snapshot(page); checks.COPY_PASTE_WORKED_END_TO_END = copied.steps[1].tokens.length === 2 && copied.steps[1].tokens[0].id !== copied.steps[1].tokens[1].id && JSON.stringify(copied.steps[1].tokens[0].warning) === JSON.stringify(copied.steps[1].tokens[1].warning);
    await page.locator("[data-editor-picture]").last().click(); await openActions(page); await page.getByRole("button", { name: "Duplicate picture", exact: true }).click(); checks.DUPLICATE_FRESH_ID = new Set((await snapshot(page)).steps[1].tokens.map((token) => token.id)).size === 3;
    await openGroup(page, 1); await openActions(page);
    const beforeGroupMove = await snapshot(page); const historyBeforeGroupMove = await page.evaluate(async () => (await import("/src/state/document.ts")).documentSession.past.peek().length);
    await page.getByRole("button", { name: "Move group earlier", exact: true }).click();
    checks.GROUP_MOVE_ONE_HISTORY_AND_BOUNDARIES = (await snapshot(page)).steps[0].id === beforeGroupMove.steps[1].id && await page.getByRole("button", { name: "Move group earlier", exact: true }).isDisabled() && historyBeforeGroupMove + 1 === await page.evaluate(async () => (await import("/src/state/document.ts")).documentSession.past.peek().length);
    await page.getByRole("button", { name: "Move group later", exact: true }).click();
    await page.getByRole("button", { name: "Remove group", exact: true }).click(); await page.getByRole("button", { name: "Cancel", exact: true }).click();
    checks.POPULATED_GROUP_CANCEL_PRESERVES_CONTENT = JSON.stringify(await snapshot(page)) === JSON.stringify(beforeGroupMove);
    await openActions(page); await page.getByRole("button", { name: "Remove group", exact: true }).click(); await page.getByRole("button", { name: "Delete", exact: true }).click(); await page.getByRole("button", { name: "Undo", exact: true }).click();
    checks.REMOVE_GROUP_UNDO_RESTORES_IDS_ATTACHMENTS = JSON.stringify(await snapshot(page)) === JSON.stringify(beforeGroupMove);
    const historyBeforePresentation = await page.evaluate(async () => (await import("/src/state/document.ts")).documentSession.past.peek().length);
    await page.getByLabel("Presentation", { exact: true }).selectOption("board");
    checks.PRESENTATION_SWITCH_ONE_HISTORY_NO_CONTENT_LOSS = (await snapshot(page)).meta.presentation === "board" && JSON.stringify((await snapshot(page)).steps) === JSON.stringify(beforeGroupMove.steps) && historyBeforePresentation + 1 === await page.evaluate(async () => (await import("/src/state/document.ts")).documentSession.past.peek().length);
    await page.getByRole("button", { name: "Undo", exact: true }).click();
    await page.locator("[data-editor-picture]").last().click(); await page.getByRole("button", { name: "Close", exact: true }).last().click();
    const selected = (await snapshot(page)).steps[1].tokens.at(-1).id;
    await page.getByRole("button", { name: "Read", exact: true }).click(); checks.PREVIEW_HIDES_EDITING_CONTROLS = await page.locator(".app-toolbar,[data-editor-picture],.app__export-canvas").count() === 0;
    await page.getByLabel("Reading content").selectOption("pictures"); checks.PICTURES_ONLY_ACCESSIBLE_NAMES = await page.getByRole("img", { name: longLabel, exact: true }).count() === 3;
    await page.keyboard.press("Control+z"); await page.getByRole("button", { name: "Back to editing", exact: true }).click();
    await page.locator("[data-editor-page]").first().waitFor(); await page.waitForFunction((id) => document.activeElement?.getAttribute("data-editor-picture") === id, selected);
    checks.READ_RETURN_FOCUS_AND_SELECTION = await page.locator(`[data-editor-picture="${selected}"]`).evaluate((node) => node === document.activeElement) && await page.evaluate(async id => (await import("/src/state/document.ts")).documentSession.selectedTokenId.peek() === id, selected);
    const exported = await downloadJson(page); checks.JSON_EXPORT_DOWNLOADS_CURRENT_DOCUMENT = JSON.stringify(exported) === JSON.stringify(await snapshot(page));
    checks.DOWNLOAD_DEFERS_OBJECT_URL_REVOKE = await page.evaluate(() => window.__downloadProbe.clicks > 0 && !window.__downloadProbe.revokedInClickTask && !window.__downloadProbe.anchorDetachedAtClick);
    const beforeImport = await snapshot(page); await page.getByLabel("Choose a JSON guide file").setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from("{not JSON") }); await page.getByRole("alert").filter({ hasText: "could not" }).waitFor(); checks.INVALID_IMPORT_PRESERVES_WORK = JSON.stringify(await snapshot(page)) === JSON.stringify(beforeImport);
    const incoming = fixture([1], "board"); incoming.meta.title = "Imported board"; await importDocument(page, incoming); checks.IMPORT_AS_NEW_AND_HISTORY_ISOLATION = await page.getByRole("button", { name: "Undo", exact: true }).isDisabled() && (await records(page)).filter(([key]) => key.startsWith("instruction-builder:guide:")).length === 2;
    await page.getByRole("button", { name: "My guides", exact: true }).click(); await page.getByRole("button", { name: "Duplicate Imported board", exact: true }).click(); await page.waitForFunction(() => document.querySelector(".guide-title input")?.value === "Imported board (copy)"); checks.GUIDE_DUPLICATE_ADDS_WORK = (await snapshot(page)).meta.title === "Imported board (copy)";
    await page.getByRole("button", { name: "My guides", exact: true }).click(); await page.getByRole("button", { name: "Delete Imported board (copy)", exact: true }).click(); await page.getByRole("dialog").getByRole("button", { name: "Delete", exact: true }).click();
    await page.getByRole("button", { name: "Restore Imported board (copy)", exact: true }).click(); checks.GUIDE_TOMBSTONE_EXACT_RESTORE = (await records(page)).filter(([key, value]) => key.startsWith("instruction-builder:guide:") && value.deletedAt === undefined).length === 3;
    await page.getByRole("button", { name: "Open Kitchen reminder", exact: true }).click(); checks.GUIDE_SWITCH_CLEARS_HISTORY = await page.getByRole("button", { name: "Undo", exact: true }).isDisabled();
    await page.screenshot({ path: path.join(out, "keyboard-editor.png"), fullPage: true });
    checks.NO_CONSOLE_OR_PAGE_ERRORS = errors.length === 0; await writeFile(path.join(out, "driver-checks.json"), JSON.stringify({ checks, errors }, null, 2)); assertChecks(checks);
  } finally { await context.close(); }
} finally { await browser.close(); }
